/* eslint-disable import/prefer-default-export */
export const AT = {
  FETCH_RECIPES_PENDING: 'FETCH_RECIPES_PENDING',
  FETCH_RECIPES_SUCCESS: 'FETCH_RECIPES_SUCCESS',
  FETCH_RECIPES_ERROR: 'FETCH_RECIPES_ERROR',
  GET_RECIPE_DETAILS: 'GET_RECIPTE_DETAILS',
  CLOSE_MODAL: 'CLOSE_MODAL',
  SEARCH_RECIPES: 'SEARCH_RECIPES'
};
